<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Anfragegrund: string
{
    case ABGRENZUNG_VON_ENERGIEMENGEN = 'ABGRENZUNG_VON_ENERGIEMENGEN';
    case ABGRENZUNG = 'ABGRENZUNG';
    case WECHSELEREIGNIS = 'WECHSELEREIGNIS';
    case ZWISCHENABLESUNG = 'ZWISCHENABLESUNG';
    case DIREKTER_VERTRAG_MSB_AN = 'DIREKTER_VERTRAG_MSB_AN';
    case DIREKTER_VERTRAG_MSB_ANN = 'DIREKTER_VERTRAG_MSB_ANN';
    case AENDERUNG_IM_LOKATIONSBUENDEL = 'AENDERUNG_IM_LOKATIONSBUENDEL';
    case NEUKONFIGURATION = 'NEUKONFIGURATION';
    case KONFIGURATION_UNVERAENDERT = 'KONFIGURATION_UNVERAENDERT';
}
