<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Berechnungsmethode: string
{
    case 24H_MITTELWERT = '24H_MITTELWERT';
    case VOM_ANBIETER_ZUR_VERFUEGUNG_GESTELLTE_AEQUIVALENTE_TAGESMITTELTEMPERATUR =
    'VOM_ANBIETER_ZUR_VERFUEGUNG_GESTELLTE_AEQUIVALENTE_TAGESMITTELTEMPERATUR';
    case AEQUIVALENTE_TAGESMITTELTEMPERATUR = 'AEQUIVALENTE_TAGESMITTELTEMPERATUR';
}
