<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum DatenstatusZeitreihe: string
{
    case ABRECHNUNGSDATEN = 'ABRECHNUNGSDATEN';
    case ABGERECHNETE_DATEN = 'ABGERECHNETE_DATEN';
    case ABRECHNUNGSDATEN_KORREKTUR_BKA = 'ABRECHNUNGSDATEN_KORREKTUR_BKA';
    case ABGERECHNETE_DATEN_KORREKTUR_BKA = 'ABGERECHNETE_DATEN_KORREKTUR_BKA';
}
