<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum DefinitionenNotwendigkeit: string
{
    case ZAEHLZEITDEFINITIONEN_WERDEN_VERWENDET = 'ZAEHLZEITDEFINITIONEN_WERDEN_VERWENDET';
    case ZAEHLZEITDEFINITIONEN_WERDEN_NICHT_VERWENDET = 'ZAEHLZEITDEFINITIONEN_WERDEN_NICHT_VERWENDET';
    case DEFINITIONEN_WERDEN_VERWENDET = 'DEFINITIONEN_WERDEN_VERWENDET';
    case DEFINITIONEN_WERDEN_NICHT_VERWENDET = 'DEFINITIONEN_WERDEN_NICHT_VERWENDET';
}
