<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum GrundlageVerringerungUmlagenGrund: string
{
    case ENFG_STROMSPEICHER_UND_VERLUSTENERGIE = 'ENFG_STROMSPEICHER_UND_VERLUSTENERGIE';
    case ENFG_ELEKTRISCH_ANGETRIEBENE_WAERMEPUMPEN = 'ENFG_ELEKTRISCH_ANGETRIEBENE_WAERMEPUMPEN';
    case ENFG_UMLAGEERH_ANL_ZUR_VERSTR_KUPPELGASEN = 'ENFG_UMLAGEERHEBUNG_BEI_ANLAGEN_ZUR_VERSTROMUNG_VON_KUPPELGASEN';
    case ENFG_HERSTELLUNG_VON_GRUENEN_WASSERSTOFF = 'ENFG_HERSTELLUNG_VON_GRUENEN_WASSERSTOFF';
    case ENFG_STROMKOSTENINTENSIVE_UNTERNEHMEN = 'ENFG_STROMKOSTENINTENSIVE_UNTERNEHMEN';
    case ENFG_HERST_WSTOFF_IN_STRMKSTINT_UNT = 'ENFG_HERSTELLUNG_VON_WASSERSTOFF_IN_STROMKOSTENINTENSIVEN_UNTERNEHMEN';
    case ENFG_SCHIENENBAHNEN = 'ENFG_SCHIENENBAHNEN';
    case ENFG_ELEKTRISCHE_BETRIEBENE_BUSSEN_IM_LINIENVERKEHR = 'ENFG_ELEKTRISCHE_BETRIEBENE_BUSSEN_IM_LINIENVERKEHR';
    case ENFG_LANDSTROMANLAGEN = 'ENFG_LANDSTROMANLAGEN';
}
