<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum ModulNetzentgelte: string
{
    case PAUSCHALE_NETZGELDREDUZIERUNG_MODUL_1 = 'PAUSCHALE_NETZGELDREDUZIERUNG_MODUL_1';
    case PROZENTUALE_REDUZIERUNG_ARBEITSPREIS_MODUL_2 = 'PROZENTUALE_REDUZIERUNG_ARBEITSPREIS_MODUL_2';
    case ANREIZMODUL_ZEITVARIABLES_NETZENTGELT_MODUL_3 = 'ANREIZMODUL_ZEITVARIABLES_NETZENTGELT_MODUL_3';
}
