<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum MSBEigenschaft: string
{
    case GRUNDZUSTAENDIGER_MESSSTELLENBETREIBER = 'GRUNDZUSTAENDIGER_MESSSTELLENBETREIBER';
    case WETTBEWERBLICHER_MESSSTELLENBETREIBER = 'WETTBEWERBLICHER_MESSSTELLENBETREIBER';
    case AUFFANGMESSSTELLENBETREIBER = 'AUFFANGMESSSTELLENBETREIBER';
}
