<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum NotwendigkeitProduktpaket: string
{
    case ZUORDNUNG_NUR_WENN_PRODUKTPAKET_UMSETZBAR = 'ZUORDNUNG_NUR_WENN_PRODUKTPAKET_UMSETZBAR';
    case ZUORDNUNG_AUCH_WENN_PRODUKTPAKET_NICHT_UMSETZBAR = 'ZUORDNUNG_AUCH_WENN_PRODUKTPAKET_NICHT_UMSETZBAR';
}
