<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Profiltyp: string
{
    case SLP_SEP = 'SLP_SEP';
    case TLP_TEP = 'TLP_TEP';
    case TEP = 'TEP';
    case GEWERBE_ALLGEMEIN = 'GEWERBE_ALLGEMEIN';
    case GEWERBE_WERKTAGS_8_18_UHR = 'GEWERBE_WERKTAGS_8_18_UHR';
    case GEWERBE_MIT_STARKEM_BIS_UEBERWIEGENDEM_VERBRAUCH_IN_DEN_ABENDSTUNDEN =
    'GEWERBE_MIT_STARKEM_BIS_UEBERWIEGENDEM_VERBRAUCH_IN_DEN_ABENDSTUNDEN';
    case GEWERBE_DURCHLAUFEND = 'GEWERBE_DURCHLAUFEND';
    case GEWERBE_LADEN_FRISEUR = 'GEWERBE_LADEN_FRISEUR';
    case GEWERBE_BAECKEREI_MIT_BACKSTUBE = 'GEWERBE_BAECKEREI_MIT_BACKSTUBE';
    case GEWERBE_WOCHENENDBETRIEB = 'GEWERBE_WOCHENENDBETRIEB';
    case LANDWIRTSCHAFTSBETRIEBE_ALLGEMEIN = 'LANDWIRTSCHAFTSBETRIEBE_ALLGEMEIN';
    case LANDWIRTSCHAFTSBETRIEBE_MIT_MILCHWIRTSCHAFT_NEBENERWERBS_TIERZUCHT =
    'LANDWIRTSCHAFTSBETRIEBE_MIT_MILCHWIRTSCHAFT_NEBENERWERBS_TIERZUCHT';
    case LANDWIRTSCHAFT_OHNE_MILCHVIEH = 'LANDWIRTSCHAFT_OHNE_MILCHVIEH';
    case HAUSHALT = 'HAUSHALT';
    case BANDLAST = 'BANDLAST';
    case UNTERBRECHBARE_VERBRAUCHSEINRICHTUNG = 'UNTERBRECHBARE_VERBRAUCHSEINRICHTUNG';
    case HEIZWAERMESPEICHER = 'HEIZWAERMESPEICHER';
    case STRASSENBELEUCHTUNG = 'STRASSENBELEUCHTUNG';
    case PHOTOVOLTAIK_MARKTLOKATION = 'PHOTOVOLTAIK_MARKTLOKATION';
    case BLOCKHEIZKRAFTWERK = 'BLOCKHEIZKRAFTWERK';
    case SONSTIGE_VERBRAUCHENDE_MARKTLOKATION = 'SONSTIGE_VERBRAUCHENDE_MARKTLOKATION';
    case SONSTIGE_ERZEUGENDE_MARKTLOKATION = 'SONSTIGE_ERZEUGENDE_MARKTLOKATION';
    case E_MOBILITAET_LADEPUNKT_IM_OEFFENTLICHEN_BEREICH = 'E_MOBILITAET_LADEPUNKT_IM_OEFFENTLICHEN_BEREICH';
    case E_MOBILITAET_LADEPUNKT_EINES_HAUSHALTS = 'E_MOBILITAET_LADEPUNKT_EINES_HAUSHALTS';
    case E_MOBILITAET_LADEPUNKT_EINES_GEWERBES = 'E_MOBILITAET_LADEPUNKT_EINES_GEWERBES';
}
