<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Reklamationsgrund: string
{
    case WERTE_ZU_HOCH = 'WERTE_ZU_HOCH';
    case WERTE_ZU_NIEDRIG = 'WERTE_ZU_NIEDRIG';
    case WERTE_FEHLEN = 'WERTE_FEHLEN';
    case KONFIGURATION_WIRKT_NICHT = 'KONFIGURATION_WIRKT_NICHT';
    case KONFIGURATION_WIRKT_TEILWEISE = 'KONFIGURATION_WIRKT_TEILWEISE';
    case WERTE_WERDEN_NICHT_NACH_VORGABEN_UEBERMITTELT = 'WERTE_WERDEN_NICHT_NACH_VORGABEN_UEBERMITTELT';
    case UEBERSICHT_FEHLT = 'UEBERSICHT_FEHLT';
    case UEBERSICHT_UNPLAUSIBEL = 'UEBERSICHT_UNPLAUSIBEL';
    case AUSGEROLLTE_DEFINITION_FEHLT = 'AUSGEROLLTE_DEFINITION_FEHLT';
    case AUSGEROLLTE_DEFINITION_UNPLAUSIBEL = 'AUSGEROLLTE_DEFINITION_UNPLAUSIBEL';
}
