<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum RessourceWechselmoeglichkeit: string
{
    case WECHSELMOEGLICHKEIT_EINMALIG_NOCH_MOEGLICH = 'WECHSELMOEGLICHKEIT_EINMALIG_NOCH_MOEGLICH';
    case WECHSELMOEGLICHKEIT_NICHT_MOEGLICH = 'WECHSELMOEGLICHKEIT_NICHT_MOEGLICH';
    case BEFRISTET_OHNE_WECHSELMOEGLICHKEIT = 'BEFRISTET_OHNE_WECHSELMOEGLICHKEIT';
    case WECHSEL_WURDE_DURCHGEFUEHRT = 'WECHSEL_WURDE_DURCHGEFUEHRT';
}
