<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Sperrauftragsverhinderungsgrund: string
{
    case RECHTLICHER_GRUND_FEHLT = 'RECHTLICHER_GRUND_FEHLT';
    case AKTIVE_ZUTRITTSVERWEIGERUNG = 'AKTIVE_ZUTRITTSVERWEIGERUNG';
    case PASSIVE_ZUTRITTSVERWEIGERUNG = 'PASSIVE_ZUTRITTSVERWEIGERUNG';
    case ANDERER_VERHINDERUNGSGRUND = 'ANDERER_VERHINDERUNGSGRUND';
    case TATSAECHLICHER_VERHINDERUNGSGRUND = 'TATSAECHLICHER_VERHINDERUNGSGRUND';
    case TECHNISCHER_VERHINDERUNGSGRUND = 'TECHNISCHER_VERHINDERUNGSGRUND';
    case ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN = 'ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN';
}
