<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Sperrauftragsablehngrund: string
{
    case DUPLIKAT = 'DUPLIKAT';
    case FALSCHER_MSB = 'FALSCHER_MSB';
    case FALSCHE_SPANNUNGSEBENE = 'FALSCHE_SPANNUNGSEBENE';
    case WEITERE_MALO_BETROFFEN = 'WEITERE_MALO_BETROFFEN';
    case ANDERER_ABLEHNGRUND = 'ANDERER_ABLEHNGRUND';
    case FRISTVERLETZUNG_TERMINGEBUNDEN = 'FRISTVERLETZUNG_TERMINGEBUNDEN';
    case FRISTVERLETZUNG_NICHT_TERMINGEBUNDEN = 'FRISTVERLETZUNG_NICHT_TERMINGEBUNDEN';
    case ANDERER_FEHLER = 'ANDERER_FEHLER';
    case LIEGT_BEREITS_VOR = 'LIEGT_BEREITS_VOR';
    case ANDERER_ZUKUENFTIGER_LIEFERANT = 'ANDERER_ZUKUENFTIGER_LIEFERANT';
    case BESTAETIGTER_LIEFERBEGINN = 'BESTAETIGTER_LIEFERBEGINN';
}
