<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Statusobjekt: string
{
    case MSBWECHSEL = 'MSBWECHSEL';
    case UMBAUMELO = 'UMBAUMELO';
    case ERSTEINBAUIMS = 'ERSTEINBAUIMS';
    case ERSTEINBAUMME = 'ERSTEINBAUMME';
    case GERAET = 'GERAET';
    case ANGEBOTANFRAGE = 'ANGEBOTANFRAGE';
    case STATUSBESTELLUNG = 'STATUSBESTELLUNG';
    case LIEFERSCHEIN = 'LIEFERSCHEIN';
    case SPERREN = 'SPERREN';
    case ENTSPERREN = 'ENTSPERREN';
    case PRIVILEGIERUNG_NACH_ENFG = 'PRIVILEGIERUNG_NACH_ENFG';
    case VERAENDERUNGSSTATUS_DER_DATEN = 'VERAENDERUNGSSTATUS_DER_DATEN';
    case TURNUSAUSLESUNG = 'TURNUSAUSLESUNG';
    case PRUEFSTATUS_ANTWORT_SUMMENZEITREIHEN = 'PRUEFSTATUS_ANTWORT_SUMMENZEITREIHEN';
    case ABWEISUNG_SUMMENZEITREIHE = 'ABWEISUNG_SUMMENZEITREIHE';
    case PRUEFSTATUS_SUMMENZEITREIHE = 'PRUEFSTATUS_SUMMENZEITREIHE';
    case DATENSTATUS_SUMMENZEITREIHE = 'DATENSTATUS_SUMMENZEITREIHE';
    case ABWEISUNG_STATUSMELDUNG_AENDERUNG = 'ABWEISUNG_STATUSMELDUNG_AENDERUNG';
    case AUSFALLARBEIT = 'AUSFALLARBEIT';
    case FAHRPLANANTEIL = 'FAHRPLANANTEIL';
    case GEGENVORSCHLAG_AUSFALLARBEIT = 'GEGENVORSCHLAG_AUSFALLARBEIT';
    case GEGENVORSCHLAG_FAHRPLANANTEIL = 'GEGENVORSCHLAG_FAHRPLANANTEIL';
}
