<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum VerwendungszweckBilanzkreis: string
{
    case VERBRAUCHENDE_MARKTLOKATION = 'VERBRAUCHENDE_MARKTLOKATION';
    case ERZEUGENDE_MARKTLOKATION_EEG = 'ERZEUGENDE_MARKTLOKATION_EEG';
    case ERZEUGENDE_MARKTLOKATION_KWKG = 'ERZEUGENDE_MARKTLOKATION_KWKG';
    case SONSTIGE_ERZEUGENDE_MARKTLOKATION = 'SONSTIGE_ERZEUGENDE_MARKTLOKATION';
}
