<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Waermenutzung: string
{
    case SPEICHERHEIZUNG = 'SPEICHERHEIZUNG';
    case WAERMEPUMPE = 'WAERMEPUMPE';
    case DIREKTHEIZUNG = 'DIREKTHEIZUNG';
    case WAERMEPUMPE_WAERME_KAELTE = 'WAERMEPUMPE_WAERME_KAELTE';
    case WAERMEPUMPE_KAELTE = 'WAERMEPUMPE_KAELTE';
    case WAERMEPUMPE_WAERME = 'WAERMEPUMPE_WAERME';
}
