<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Zeitreihentyp: string
{
    case EGS = 'EGS';
    case LGS = 'LGS';
    case NZR = 'NZR';
    case SES = 'SES';
    case SLS = 'SLS';
    case TES = 'TES';
    case TLS = 'TLS';
    case SLS_TLS = 'SLS_TLS';
    case SES_TES = 'SES_TES';
    case AUS = 'AUS';
    case BAS = 'BAS';
    case DBA = 'DBA';
    case DZR = 'DZR';
    case DZUE = 'DZÜ';
    case FPE = 'FPE';
    case FPI = 'FPI';
    case SRE = 'SRE';
    case SRI = 'SRI';
    case VZR = 'VZR';
    case BIL = 'BIL';
    case BIP = 'BIP';
    case BIT = 'BIT';
    case GAL = 'GAL';
    case GAP = 'GAP';
    case GAT = 'GAT';
    case GEL = 'GEL';
    case GEP = 'GEP';
    case GET = 'GET';
    case SOL = 'SOL';
    case SOP = 'SOP';
    case SOT = 'SOT';
    case WFL = 'WFL';
    case WFP = 'WFP';
    case WNL = 'WNL';
    case WNP = 'WNP';
    case WNT = 'WNT';
    case WAL = 'WAL';
    case WAP = 'WAP';
    case WAT = 'WAT';
    case AU1 = 'AU1';
    case BI1 = 'BI1';
    case BI2 = 'BI2';
    case BI3 = 'BI3';
    case GAA = 'GAA';
    case GAB = 'GAB';
    case GAC = 'GAC';
    case GE1 = 'GE1';
    case GE2 = 'GE2';
    case GE3 = 'GE3';
    case SO1 = 'SO1';
    case SO2 = 'SO2';
    case SO3 = 'SO3';
    case WF1 = 'WF1';
    case WF2 = 'WF2';
    case WF3 = 'WF3';
    case WN1 = 'WN1';
    case WN2 = 'WN2';
    case WN3 = 'WN3';
    case WAA = 'WAA';
    case WAB = 'WAB';
    case WAC = 'WAC';
    case AUSFALLARBEITSSUMME = 'AUSFALLARBEITSSUMME';
    case BILANZKREISABWEICHUNGSSALDO = 'BILANZKREISABWEICHUNGSSALDO';
    case DIFFERENZZEITREIHE = 'DIFFERENZZEITREIHE';
    case DELTAZEITREIHE = 'DELTAZEITREIHE';
    case DELTAZEITREIHENUEBERTRAG = 'DELTAZEITREIHENUEBERTRAG';
    case FAHRPLANENTNAHMESUMME = 'FAHRPLANENTNAHMESUMME';
    case FAHRPLANEINSPEISESUMME = 'FAHRPLANEINSPEISESUMME';
    case UEBERFUEHRUNGSZEITREIHE_SEKUNDAERREGELLEISTUNG_EXPORT =
    'UEBERFUEHRUNGSZEITREIHE_SEKUNDAERREGELLEISTUNG_EXPORT';
    case UEBERFUEHRUNGSZEITREIHE_SEKUNDAERREGELLEISTUNG_IMPORT =
    'UEBERFUEHRUNGSZEITREIHE_SEKUNDAERREGELLEISTUNG_IMPORT';
    case VERLUSTZEITREIHE = 'VERLUSTZEITREIHE';
    case EE_EINSPEISESUMME_BIOMASSE_BIOGAS_GEMESSEN = 'EE_EINSPEISESUMME_BIOMASSE_BIOGAS_GEMESSEN';
    case EE_EINSPEISESUMME_BIOMASSE_BIOGAS_EINSPEISEPROFIL = 'EE_EINSPEISESUMME_BIOMASSE_BIOGAS_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_BIOMASSE_BIOGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_BIOMASSE_BIOGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_DEPONIE_KLAER_GRUBENGAS_GEMESSEN = 'EE_EINSPEISESUMME_DEPONIE_KLAER_GRUBENGAS_GEMESSEN';
    case EE_EINSPEISESUMME_DEPONIE_KLAER_GRUBENGAS_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_DEPONIE_KLAER_GRUBENGAS_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_DEPONIE_KLAER_GRUBENGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_DEPONIE_KLAER_GRUBENGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_GEOTHERMIE_GEMESSEN = 'EE_EINSPEISESUMME_GEOTHERMIE_GEMESSEN';
    case EE_EINSPEISESUMME_GEOTHERMIE_EINSPEISEPROFIL = 'EE_EINSPEISESUMME_GEOTHERMIE_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_GEOTHERMIE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_GEOTHERMIE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_SOLAR_GEMESSEN = 'EE_EINSPEISESUMME_SOLAR_GEMESSEN';
    case EE_EINSPEISESUMME_SOLAR_EINSPEISEPROFIL = 'EE_EINSPEISESUMME_SOLAR_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_SOLAR_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_SOLAR_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_WIND_OFFSHORE_GEMESSEN = 'EE_EINSPEISESUMME_WIND_OFFSHORE_GEMESSEN';
    case EE_EINSPEISESUMME_WIND_OFFSHORE_EINSPEISEPROFIL = 'EE_EINSPEISESUMME_WIND_OFFSHORE_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_WIND_OFFSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_WIND_OFFSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_WIND_ONSHORE_GEMESSEN = 'EE_EINSPEISESUMME_WIND_ONSHORE_GEMESSEN';
    case EE_EINSPEISESUMME_WIND_ONSHORE_EINSPEISEPROFIL = 'EE_EINSPEISESUMME_WIND_ONSHORE_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_WIND_ONSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_WIND_ONSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_WASSERKRAFT_GEMESSEN = 'EE_EINSPEISESUMME_WASSERKRAFT_GEMESSEN';
    case EE_EINSPEISESUMME_WASSERKRAFT_EINSPEISEPROFIL = 'EE_EINSPEISESUMME_WASSERKRAFT_EINSPEISEPROFIL';
    case EE_EINSPEISESUMME_WASSERKRAFT_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EE_EINSPEISESUMME_WASSERKRAFT_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_AUSFALLARBEIT = 'EEG_UEBERFUEHRUNG_AUSFALLARBEIT';
    case EEG_UEBERFUEHRUNG_BIOMASSE_BIOGAS_WERTE = 'EEG_UEBERFUEHRUNG_BIOMASSE_BIOGAS_WERTE';
    case EEG_UEBERFUEHRUNG_BIOMASSE_BIOGAS_STANDARDEINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_BIOMASSE_BIOGAS_STANDARDEINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_BIOMASSE_BIOGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_BIOMASSE_BIOGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_DEPONIE_KLAER_GRUBENGAS_WERTE = 'EEG_UEBERFUEHRUNG_DEPONIE_KLAER_GRUBENGAS_WERTE';
    case EEG_UEBERFUEHRUNG_DEPONIE_KLAER_GRUBENGAS_STANDARDEINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_DEPONIE_KLAER_GRUBENGAS_STANDARDEINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_DEPONIE_KLAER_GRUBENGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_DEPONIE_KLAER_GRUBENGAS_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_GEOTHERMIE_WERTE = 'EEG_UEBERFUEHRUNG_GEOTHERMIE_WERTE';
    case EEG_UEBERFUEHRUNG_GEOTHERMIE_STANDARDEINSPEISEPROFIL = 'EEG_UEBERFUEHRUNG_GEOTHERMIE_STANDARDEINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_GEOTHERMIE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_GEOTHERMIE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_SOLAR_WERTE = 'EEG_UEBERFUEHRUNG_SOLAR_WERTE';
    case EEG_UEBERFUEHRUNG_SOLAR_STANDARDEINSPEISEPROFIL = 'EEG_UEBERFUEHRUNG_SOLAR_STANDARDEINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_SOLAR_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_SOLAR_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_WIND_OFFSHORE_WERTE = 'EEG_UEBERFUEHRUNG_WIND_OFFSHORE_WERTE';
    case EEG_UEBERFUEHRUNG_WIND_OFFSHORE_STANDARDEINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_WIND_OFFSHORE_STANDARDEINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_WIND_OFFSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_WIND_OFFSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_WIND_ONSHORE_WERTE = 'EEG_UEBERFUEHRUNG_WIND_ONSHORE_WERTE';
    case EEG_UEBERFUEHRUNG_WIND_ONSHORE_STANDARDEINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_WIND_ONSHORE_STANDARDEINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_WIND_ONSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_WIND_ONSHORE_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_WASSERKRAFT_WERTE = 'EEG_UEBERFUEHRUNG_WASSERKRAFT_WERTE';
    case EEG_UEBERFUEHRUNG_WASSERKRAFT_STANDARDEINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_WASSERKRAFT_STANDARDEINSPEISEPROFIL';
    case EEG_UEBERFUEHRUNG_WASSERKRAFT_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL =
    'EEG_UEBERFUEHRUNG_WASSERKRAFT_TAGESPARAMETERABHAENGIGES_EINSPEISEPROFIL';
}
