<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Abweichungsgrund
{
    public const PREIS_RECHENREGEL_FALSCH = 'PREIS_RECHENREGEL_FALSCH';
    public const FALSCHER_ABRECHNUNGSZEITRAUM = 'FALSCHER_ABRECHNUNGSZEITRAUM';
    public const UNBEKANNTE_MARKTLOKATION_MESSLOKATION = 'UNBEKANNTE_MARKTLOKATION_MESSLOKATION';
    public const SONSTIGER_ABWEICHUNGSGRUND = 'SONSTIGER_ABWEICHUNGSGRUND';
    public const DOPPELTE_RECHNUNG = 'DOPPELTE_RECHNUNG';
    public const ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN = 'ABRECHNUNGSBEGINN_UNGLEICH_VERTRAGSBEGINN';
    public const ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE = 'ABRECHNUNGSENDE_UNGLEICH_VERTRAGSENDE';
    public const BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH = 'BETRAG_DER_ABSCHLAGSRECHNUNG_FALSCH';
    public const VORAUSBEZAHLTER_BETRAG_FALSCH = 'VORAUSBEZAHLTER_BETRAG_FALSCH';
    public const ARTIKEL_NICHT_VEREINBART = 'ARTIKEL_NICHT_VEREINBART';
    public const NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN = 'NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FEHLEN';
    public const RECHNUNGSNUMMER_BEREITS_ERHALTEN = 'RECHNUNGSNUMMER_BEREITS_ERHALTEN';
    public const NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH = 'NETZNUTZUNGSMESSWERTE_ENERGIEMENGEN_FALSCH';
    public const ZEITLICHE_MENGENANGABE_FEHLERHAFT = 'ZEITLICHE_MENGENANGABE_FEHLERHAFT';
    public const FALSCHER_BILANZIERUNGSBEGINN = 'FALSCHER_BILANZIERUNGSBEGINN';
    public const FALSCHES_NETZNUTZUNGSENDE = 'FALSCHES_NETZNUTZUNGSENDE';
    public const BILANZIERTE_MENGE_FEHLT = 'BILANZIERTE_MENGE_FEHLT';
    public const BILANZIERTE_MENGE_FALSCH = 'BILANZIERTE_MENGE_FALSCH';
    public const NETZNUTZUNGSABRECHNUNG_FEHLT = 'NETZNUTZUNGSABRECHNUNG_FEHLT';
    public const REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT = 'REVERSE_CHARGE_ANWENDUNG_FEHLT_ODER_FEHLERHAFT';
    public const ALLOKATIONSLISTE_FEHLT = 'ALLOKATIONSLISTE_FEHLT';
    public const MEHR_MINDERMENGE_FALSCH = 'MEHR_MINDERMENGE_FALSCH';
    public const UNGUELTIGES_RECHNUNGSDATUM = 'UNGUELTIGES_RECHNUNGSDATUM';
    public const ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT = 'ZEITINTERVALL_DER_BILANZIERTEN_MENGE_INKONSISTENT';
    public const RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS = 'RECHNUNGSEMPFAENGER_WIDERSPRICHT_DER_STEUERRECHTLICHEN_EINSCHAETZUNG_DES_RECHNUNGSSTELLERS';
    public const ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN = 'ANGEGEBENE_QUOTES_AN_MARKTLOKATION_NICHT_VORHANDEN';
    public const RECHNUNGSABWICKLUNG_NICHT_VEREINBART = 'RECHNUNGSABWICKLUNG_NICHT_VEREINBART';
    public const COMDIS_WIRD_ABGELEHNT = 'COMDIS_WIRD_ABGELEHNT';
}
