<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Anfragetyp
{
    public const START_ABO = 'START_ABO';
    public const ENDE_ABO = 'ENDE_ABO';
    public const OHNE_ABO = 'OHNE_ABO';
    public const KAUF = 'KAUF';
    public const NUTZUNGSUEBERLASSUNG = 'NUTZUNGSUEBERLASSUNG';
    public const ABRECHNUNGSBRENNWERT_UND_ZUSTANDSZAHL = 'ABRECHNUNGSBRENNWERT_UND_ZUSTANDSZAHL';
    public const LASTGANGDATEN = 'LASTGANGDATEN';
    public const ZAEHLERSTAENDE = 'ZAEHLERSTAENDE';
    public const WERTEERMITTLUNG = 'WERTEERMITTLUNG';
    public const ENERGIEMENGE_EINZELWERT = 'ENERGIEMENGE_EINZELWERT';
    public const INNERHALB_DER_ARBEITSZEIT = 'INNERHALB_DER_ARBEITSZEIT';
    public const AUCH_AUSSERHALB_DER_ARBEITSZEIT = 'AUCH_AUSSERHALB_DER_ARBEITSZEIT';
    public const WECHSEL_SAEMTLICHER_EINRICHTUNGEN = 'WECHSEL_SAEMTLICHER_EINRICHTUNGEN';
    public const TEILWEISER_WECHSEL = 'TEILWEISER_WECHSEL';
    public const AENDERUNG_ZAEHLZEITDEFINITION = 'AENDERUNG_ZAEHLZEITDEFINITION';
    public const ABBESTELLUNG_ZAEHLZEITEN = 'ABBESTELLUNG_ZAEHLZEITEN';
    public const ABBESTELLUNG_MESSPRODUKT = 'ABBESTELLUNG_MESSPRODUKT';
    public const ANGEBOT_AUF_BASIS_PREISBLATT = 'ANGEBOT_AUF_BASIS_PREISBLATT';
    public const INDIVIDUELLES_ANGEBOT = 'INDIVIDUELLES_ANGEBOT';
}
