<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface BDEWArtikelnummer
{
    public const LEISTUNG = 'LEISTUNG';
    public const LEISTUNG_PAUSCHAL = 'LEISTUNG_PAUSCHAL';
    public const GRUNDPREIS = 'GRUNDPREIS';
    public const REGELENERGIE_ARBEIT = 'REGELENERGIE_ARBEIT';
    public const REGELENERGIE_LEISTUNG = 'REGELENERGIE_LEISTUNG';
    public const NOTSTROMLIEFERUNG_ARBEIT = 'NOTSTROMLIEFERUNG_ARBEIT';
    public const NOTSTROMLIEFERUNG_LEISTUNG = 'NOTSTROMLIEFERUNG_LEISTUNG';
    public const RESERVENETZKAPAZITAET = 'RESERVENETZKAPAZITAET';
    public const RESERVELEISTUNG = 'RESERVELEISTUNG';
    public const ZUSAETZLICHE_ABLESUNG = 'ZUSAETZLICHE_ABLESUNG';
    public const PRUEFGEBUEHREN_AUSSERPLANMAESSIG = 'PRUEFGEBUEHREN_AUSSERPLANMAESSIG';
    public const WIRKARBEIT = 'WIRKARBEIT';
    public const SINGULAER_GENUTZTE_BETRIEBSMITTEL = 'SINGULAER_GENUTZTE_BETRIEBSMITTEL';
    public const ABGABE_KWKG = 'ABGABE_KWKG';
    public const ABSCHLAG = 'ABSCHLAG';
    public const KONZESSIONSABGABE = 'KONZESSIONSABGABE';
    public const ENTGELT_FERNAUSLESUNG = 'ENTGELT_FERNAUSLESUNG';
    public const UNTERMESSUNG = 'UNTERMESSUNG';
    public const BLINDMEHRARBEIT = 'BLINDMEHRARBEIT';
    public const ENTGELT_ABRECHNUNG = 'ENTGELT_ABRECHNUNG';
    public const SPERRKOSTEN = 'SPERRKOSTEN';
    public const ENTSPERRKOSTEN = 'ENTSPERRKOSTEN';
    public const MAHNKOSTEN = 'MAHNKOSTEN';
    public const MEHR_MINDERMENGEN = 'MEHR_MINDERMENGEN';
    public const INKASSOKOSTEN = 'INKASSOKOSTEN';
    public const BLINDMEHRLEISTUNG = 'BLINDMEHRLEISTUNG';
    public const ENTGELT_MESSUNG_ABLESUNG = 'ENTGELT_MESSUNG_ABLESUNG';
    public const ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK = 'ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK';
    public const AUSGLEICHSENERGIE = 'AUSGLEICHSENERGIE';
    public const AUSGLEICHSENERGIE_UNTERDECKUNG = 'AUSGLEICHSENERGIE_UNTERDECKUNG';
    public const ZAEHLEINRICHTUNG = 'ZAEHLEINRICHTUNG';
    public const WANDLER_MENGENUMWERTER = 'WANDLER_MENGENUMWERTER';
    public const KOMMUNIKATIONSEINRICHTUNG = 'KOMMUNIKATIONSEINRICHTUNG';
    public const TECHNISCHE_STEUEREINRICHTUNG = 'TECHNISCHE_STEUEREINRICHTUNG';
    public const PARAGRAF_19_STROM_NEV_UMLAGE = 'PARAGRAF_19_STROM_NEV_UMLAGE';
    public const BEFESTIGUNGSEINRICHTUNG = 'BEFESTIGUNGSEINRICHTUNG';
    public const OFFSHORE_HAFTUNGSUMLAGE = 'OFFSHORE_HAFTUNGSUMLAGE';
    public const FIXE_ARBEITSENTGELTKOMPONENTE = 'FIXE_ARBEITSENTGELTKOMPONENTE';
    public const FIXE_LEISTUNGSENTGELTKOMPONENTE = 'FIXE_LEISTUNGSENTGELTKOMPONENTE';
    public const UMLAGE_ABSCHALTBARE_LASTEN = 'UMLAGE_ABSCHALTBARE_LASTEN';
    public const MEHRMENGE = 'MEHRMENGE';
    public const MINDERMENGE = 'MINDERMENGE';
    public const ENERGIESTEUER = 'ENERGIESTEUER';
    public const SMARTMETER_GATEWAY = 'SMARTMETER_GATEWAY';
    public const STEUERBOX = 'STEUERBOX';
    public const MSB_INKL_MESSUNG = 'MSB_INKL_MESSUNG';
    public const ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG';
    public const ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG';
    public const ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG';
    public const ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG';
    public const ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG';
    public const ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG';
}
