<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface BerechnungsformelNotwendigkeit
{
    public const BERECHNUNGSFORMEL_NOTWENDIG = 'BERECHNUNGSFORMEL_NOTWENDIG';
    public const BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN = 'BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN';
    public const BERECHNUNGSFORMEL_TRIVIAL = 'BERECHNUNGSFORMEL_TRIVIAL';
    public const BERECHNUNGSFORMEL_NICHT_NOTWENDIG = 'BERECHNUNGSFORMEL_NICHT_NOTWENDIG';
}
