<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface DefinitionenNotwendigkeit
{
    public const ZAEHLZEITDEFINITIONEN_WERDEN_VERWENDET = 'ZAEHLZEITDEFINITIONEN_WERDEN_VERWENDET';
    public const ZAEHLZEITDEFINITIONEN_WERDEN_NICHT_VERWENDET = 'ZAEHLZEITDEFINITIONEN_WERDEN_NICHT_VERWENDET';
    public const DEFINITIONEN_WERDEN_VERWENDET = 'DEFINITIONEN_WERDEN_VERWENDET';
    public const DEFINITIONEN_WERDEN_NICHT_VERWENDET = 'DEFINITIONEN_WERDEN_NICHT_VERWENDET';
}
