<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Dienstleistungstyp
{
    public const DATENBEREITSTELLUNG_TAEGLICH = 'DATENBEREITSTELLUNG_TAEGLICH';
    public const DATENBEREITSTELLUNG_WOECHENTLICH = 'DATENBEREITSTELLUNG_WOECHENTLICH';
    public const DATENBEREITSTELLUNG_MONATLICH = 'DATENBEREITSTELLUNG_MONATLICH';
    public const DATENBEREITSTELLUNG_JAEHRLICH = 'DATENBEREITSTELLUNG_JAEHRLICH';
    public const DATENBEREITSTELLUNG_HISTORISCHE_LG = 'DATENBEREITSTELLUNG_HISTORISCHE_LG';
    public const DATENBEREITSTELLUNG_STUENDLICH = 'DATENBEREITSTELLUNG_STUENDLICH';
    public const DATENBEREITSTELLUNG_VIERTELJAEHRLICH = 'DATENBEREITSTELLUNG_VIERTELJAEHRLICH';
    public const DATENBEREITSTELLUNG_HALBJAEHRLICH = 'DATENBEREITSTELLUNG_HALBJAEHRLICH';
    public const DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH = 'DATENBEREITSTELLUNG_MONATLICH_ZUSAETZLICH';
    public const DATENBEREITSTELLUNG_EINMALIG = 'DATENBEREITSTELLUNG_EINMALIG';
    public const AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG = 'AUSLESUNG_2X_TAEGLICH_FERNAUSLESUNG';
    public const AUSLESUNG_TAEGLICH_FERNAUSLESUNG = 'AUSLESUNG_TAEGLICH_FERNAUSLESUNG';
    public const AUSLESUNG_LGK_MANUELL_MSB = 'AUSLESUNG_LGK_MANUELL_MSB';
    public const AUSLESUNG_MONATLICH_SLP_FERNAUSLESUNG = 'AUSLESUNG_MONATLICH_SLP_FERNAUSLESUNG';
    public const AUSLESUNG_JAEHRLICH_SLP_FERNAUSLESUNG = 'AUSLESUNG_JAEHRLICH_SLP_FERNAUSLESUNG';
    public const AUSLESUNG_MDE_SLP = 'AUSLESUNG_MDE_SLP';
    public const ABLESUNG_MONATLICH_SLP = 'ABLESUNG_MONATLICH_SLP';
    public const ABLESUNG_VIERTELJAEHRLICH_SLP = 'ABLESUNG_VIERTELJAEHRLICH_SLP';
    public const ABLESUNG_HALBJAEHRLICH_SLP = 'ABLESUNG_HALBJAEHRLICH_SLP';
    public const ABLESUNG_JAEHRLICH_SLP = 'ABLESUNG_JAEHRLICH_SLP';
    public const AUSLESUNG_SLP_FERNAUSLESUNG = 'AUSLESUNG_SLP_FERNAUSLESUNG';
    public const ABLESUNG_SLP_ZUSAETZLICH_MSB = 'ABLESUNG_SLP_ZUSAETZLICH_MSB';
    public const ABLESUNG_SLP_ZUSAETZLICH_KUNDE = 'ABLESUNG_SLP_ZUSAETZLICH_KUNDE';
    public const AUSLESUNG_LGK_FERNAUSLESUNG_ZUSAETZLICH_MSB = 'AUSLESUNG_LGK_FERNAUSLESUNG_ZUSAETZLICH_MSB';
    public const AUSLESUNG_MOATLICH_FERNAUSLESUNG = 'AUSLESUNG_MOATLICH_FERNAUSLESUNG';
    public const AUSLESUNG_STUENDLICH_FERNAUSLESUNG = 'AUSLESUNG_STUENDLICH_FERNAUSLESUNG';
    public const ABLESUNG_MONATLICH_LGK = 'ABLESUNG_MONATLICH_LGK';
    public const AUSLESUNG_TEMERATURMENGENUMWERTER = 'AUSLESUNG_TEMERATURMENGENUMWERTER';
    public const AUSLESUNG_ZUSTANDSMENGENUMWERTER = 'AUSLESUNG_ZUSTANDSMENGENUMWERTER';
    public const AUSLESUNG_SYSTEMMENGENUMWERTER = 'AUSLESUNG_SYSTEMMENGENUMWERTER';
    public const AUSLESUNG_VORGANG_SLP = 'AUSLESUNG_VORGANG_SLP';
    public const AUSLESUUNG_KOMPAKTMENGENUMWERTER = 'AUSLESUUNG_KOMPAKTMENGENUMWERTER';
    public const AUSLESUNG_MDE_LGK = 'AUSLESUNG_MDE_LGK';
    public const SPERRUNG_SLP = 'SPERRUNG_SLP';
    public const ENTSPERRUNG_SLP = 'ENTSPERRUNG_SLP';
    public const SPERRUNG_RLM = 'SPERRUNG_RLM';
    public const ENTSPERRUNG_RLM = 'ENTSPERRUNG_RLM';
    public const MAHNKOSTEN = 'MAHNKOSTEN';
    public const INKASSOKOSTEN = 'INKASSOKOSTEN';
}
