<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface FehlerCode
{
    public const ID_UNBEKANNT = "ID_UNBEKANNT";
    public const ABSENDER_NICHT_ZUGEORDNET = "ABSENDER_NICHT_ZUGEORDNET";
    public const EMPFAENGER_NICHT_ZUGEORDNET = "EMPFAENGER_NICHT_ZUGEORDNET";
    public const GERAET_UNBEKANNT = "GERAET_UNBEKANNT";
    public const OBIS_UNBEKANNT = "OBIS_UNBEKANNT";
    public const REFERENZIERUNG_FEHLERHAFT = "REFERENZIERUNG_FEHLERHAFT";
    public const TUPEL_UNBEKANNT = "TUPEL_UNBEKANNT";
    public const ABSENDER_TUPEL_NICHT_ZUGEORDNET = "ABSENDER_TUPEL_NICHT_ZUGEORDNET";
    public const EMPFAENGER_TUPEL_NICHT_ZUGEORDNET = "EMPFAENGER_TUPEL_NICHT_ZUGEORDNET";
    public const VORKOMMA_ZU_VIELE_STELLEN = "VORKOMMA_ZU_VIELE_STELLEN";
    public const ZEITREIHE_UNVOLLSTAENDIG = "ZEITREIHE_UNVOLLSTAENDIG";
    public const REFERENZIERTES_TUPEL_UNBEKANNT = "REFERENZIERTES_TUPEL_UNBEKANNT";
    public const MARKTLOKATION_UNBEKANNT = "MARKTLOKATION_UNBEKANNT";
    public const MESSLOKATION_UNBEKANNT = "MESSLOKATION_UNBEKANNT";
    public const MELDEPUNKT_NICHT_MEHR_IM_NETZ = "MELDEPUNKT_NICHT_MEHR_IM_NETZ";
    public const ERFORDERLICHE_ANGABE_FEHLT = "ERFORDERLICHE_ANGABE_FEHLT";
    public const GESCHAEFTSVORFALL_ZURUECKGEWIESEN = "GESCHAEFTSVORFALL_ZURUECKGEWIESEN";
    public const ZEITINTERVALL_NEGATIV = "ZEITINTERVALL_NEGATIV";
    public const FORMAT_NICHT_EINGEHALTEN = "FORMAT_NICHT_EINGEHALTEN";
    public const GESCHAEFTSVORFALL_ABSENDER = "GESCHAEFTSVORFALL_ABSENDER";
    public const KONFIGURATIONSID_UNBEKANNT = "KONFIGURATIONSID_UNBEKANNT";
    public const SEGMENTWIEDERHOLUNG_UEBERSCHRITTEN = "SEGMENTWIEDERHOLUNG_UEBERSCHRITTEN";
    public const ANZAHLCODES_UEBERSCHRITTEN = "ANZAHLCODES_UEBERSCHRITTEN";
    public const ZEITANGABE_UNPLAUSIBEL = "ZEITANGABE_UNPLAUSIBEL";
    public const CODE_NICHT_ERLAUBT = "CODE_NICHT_ERLAUBT";
    public const OBJEKT_NICHT_GEFUNDEN = "OBJEKT_NICHT_GEFUNDEN";
    public const OBJEKT_NICHT_EINDEUTIG = "OBJEKT_NICHT_EINDEUTIG";
}
