<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Geraetetyp
{
    public const WECHSELSTROMZAEHLER = 'WECHSELSTROMZAEHLER';
    public const DREHSTROMZAEHLER = 'DREHSTROMZAEHLER';
    public const ZWEIRICHTUNGSZAEHLER = 'ZWEIRICHTUNGSZAEHLER';
    public const RLM_ZAEHLER = 'RLM_ZAEHLER';
    public const IMS_ZAEHLER = 'IMS_ZAEHLER';
    public const BALGENGASZAEHLER = 'BALGENGASZAEHLER';
    public const MAXIMUMZAEHLER = 'MAXIMUMZAEHLER';
    public const MULTIPLEXANLAGE = 'MULTIPLEXANLAGE';
    public const PAUSCHALANLAGE = 'PAUSCHALANLAGE';
    public const VERSTAERKERANLAGE = 'VERSTAERKERANLAGE';
    public const SUMMATIONSGERAET = 'SUMMATIONSGERAET';
    public const IMPULSGEBER = 'IMPULSGEBER';
    public const EDL_21_ZAEHLERAUFSATZ = 'EDL_21_ZAEHLERAUFSATZ';
    public const VIER_QUADRANTEN_LASTGANGZAEHLER = 'VIER_QUADRANTEN_LASTGANGZAEHLER';
    public const MENGENUMWERTER = 'MENGENUMWERTER';
    public const STROMWANDLER = 'STROMWANDLER';
    public const SPANNUNGSWANDLER = 'SPANNUNGSWANDLER';
    public const DATENLOGGER = 'DATENLOGGER';
    public const KOMMUNIKATIONSANSCHLUSS = 'KOMMUNIKATIONSANSCHLUSS';
    public const MODEM = 'MODEM';
    public const TELEKOMMUNIKATIONSEINRICHTUNG = 'TELEKOMMUNIKATIONSEINRICHTUNG';
    public const KOMMUNIKATIONSEINRICHTUNG = 'KOMMUNIKATIONSEINRICHTUNG';
    public const DREHKOLBENGASZAEHLER = 'DREHKOLBENGASZAEHLER';
    public const TURBINENRADGASZAEHLER = 'TURBINENRADGASZAEHLER';
    public const ULTRASCHALLZAEHLER = 'ULTRASCHALLZAEHLER';
    public const WIRBELGASZAEHLER = 'WIRBELGASZAEHLER';
    public const MODERNE_MESSEINRICHTUNG = 'MODERNE_MESSEINRICHTUNG';
    public const ELEKTRONISCHER_HAUSHALTSZAEHLER = 'ELEKTRONISCHER_HAUSHALTSZAEHLER';
    public const STEUEREINRICHTUNG = 'STEUEREINRICHTUNG';
    public const TECHNISCHESTEUEREINRICHTUNG = 'TECHNISCHESTEUEREINRICHTUNG';
    public const TARIFSCHALTGERAET = 'TARIFSCHALTGERAET';
    public const RUNDSTEUEREMPFAENGER = 'RUNDSTEUEREMPFAENGER';
    public const OPTIONALE_ZUS_ZAEHLEINRICHTUNG = 'OPTIONALE_ZUS_ZAEHLEINRICHTUNG';
    public const MESSWANDLERSATZ_IMS_MME = 'MESSWANDLERSATZ_IMS_MME';
    public const KOMBIMESSWANDLER_IMS_MME = 'KOMBIMESSWANDLER_IMS_MME';
    public const TARIFSCHALTGERAET_IMS_MME = 'TARIFSCHALTGERAET_IMS_MME';
    public const RUNDSTEUEREMPFAENGER_IMS_MME = 'RUNDSTEUEREMPFAENGER_IMS_MME';
    public const TEMPERATUR_KOMPENSATION = 'TEMPERATUR_KOMPENSATION';
    public const HOECHSTBELASTUNGS_ANZEIGER = 'HOECHSTBELASTUNGS_ANZEIGER';
    public const SONSTIGES_GERAET = 'SONSTIGES_GERAET';
    public const SMARTMETERGATEWAY = 'SMARTMETERGATEWAY';
    public const STEUERBOX = 'STEUERBOX';
    public const BLOCKSTROMWANDLER = 'BLOCKSTROMWANDLER';
    public const KOMBIMESSWANDLER = 'KOMBIMESSWANDLER';
    public const MODEM_GSM = 'MODEM_GSM';
    public const ETHERNET_KOM = 'ETHERNET_KOM';
    public const PLC_COM = 'PLC_COM';
    public const MODEM_FESTNETZ = 'MODEM_FESTNETZ';
    public const DSL_KOM = 'DSL_KOM';
    public const LTE_KOM = 'LTE_KOM';
    public const DICHTEMENGENUMWERTER = 'DICHTEMENGENUMWERTER';
    public const TEMPERATURMENGENUMWERTER = 'TEMPERATURMENGENUMWERTER';
    public const ZUSTANDSMENGENUMWERTER = 'ZUSTANDSMENGENUMWERTER';
    public const MESSDATENREGISTRIERGERAET = 'MESSDATENREGISTRIERGERAET';
    public const WANDLER = 'WANDLER';
}
