<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Handelsunstimmigkeitstyp
{
    public const HANDELSRECHNUNG = 'HANDELSRECHNUNG';
    public const LIEFERSCHEIN_HANDELSUNSTIMMIGKEITSTYP = 'LIEFERSCHEIN_HANDELSUNSTIMMIGKEITSTYP';
    public const LIEFERSCHEIN_GRUND_ARBEITSPREIS = 'LIEFERSCHEIN_GRUND_ARBEITSPREIS';
    public const LIEFERSCHEIN_ARBEITS_LEISTUNGSPREIS = 'LIEFERSCHEIN_ARBEITS_LEISTUNGSPREIS';
}
