<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Handelsunstimmigkeitsgrund
{
    public const ANMELDUNG_BESTAETIGT = 'ANMELDUNG_BESTAETIGT';
    public const ABRECHNUNGSBEGINN_GLEICH_BESTAETIGTEM_VERTRAGSBEGINN = 'ABRECHNUNGSBEGINN_GLEICH_BESTAETIGTEM_VERTRAGSBEGINN';
    public const ABRECHNUNGSENDE_GLEICH_BESTAETIGTEM_VERTRAGSENDE = 'ABRECHNUNGSENDE_GLEICH_BESTAETIGTEM_VERTRAGSENDE';
    public const NN_MSCONS_UEBERSENDET = 'NN_MSCONS_UEBERSENDET';
    public const RICHTIGE_MESSWERTE_ENERGIEMENGEN_UEBERSENDET = 'RICHTIGE_MESSWERTE_ENERGIEMENGEN_UEBERSENDET';
    public const SONSTIGES_SIEHE_BEGRUENDUNG = 'SONSTIGES_SIEHE_BEGRUENDUNG';
    public const GUELTIGES_PREISBLATT_VERSENDET = 'GUELTIGES_PREISBLATT_VERSENDET';
    public const GUELTIGER_SPERRAUFTRAG_VORHANDEN = 'GUELTIGER_SPERRAUFTRAG_VORHANDEN';
    public const KORREKTE_ARTIKEL_ID_IN_RECHNUNG = 'KORREKTE_ARTIKEL_ID_IN_RECHNUNG';
    public const KORREKTER_PREIS_ZU_GUELTIGEM_PREISBLATT_IN_RECHNUNG = 'KORREKTER_PREIS_ZU_GUELTIGEM_PREISBLATT_IN_RECHNUNG';
    public const RECHNUNG_KORREKT_A05 = 'RECHNUNG_KORREKT_A05';
    public const RECHNUNG_KORREKT_A10 = 'RECHNUNG_KORREKT_A10';
    public const RECHNUNG_KORREKT_A11 = 'RECHNUNG_KORREKT_A11';
    public const GUELTIGES_PREISBLATT_FRISTGERECHT_VERSENDET = 'GUELTIGES_PREISBLATT_FRISTGERECHT_VERSENDET';
    public const GUELTIGE_RECHNUNG_VORHANDEN = 'GUELTIGE_RECHNUNG_VORHANDEN';
    public const ARTIKEL_ID_FUER_VERZUGSKOSTEN_VERWENDET = 'ARTIKEL_ID_FUER_VERZUGSKOSTEN_VERWENDET';
    public const KORREKTER_PREIS_IN_RECHNUNG_ABGERECHNET = 'KORREKTER_PREIS_IN_RECHNUNG_ABGERECHNET';
    public const GUELTIGES_PREISBLATT_BLINDARBEIT_VERSENDET = 'GUELTIGES_PREISBLATT_BLINDARBEIT_VERSENDET';
    public const KORREKTE_ARTIKEL_ID_IST_ANGEGEBEN = 'KORREKTE_ARTIKEL_ID_IST_ANGEGEBEN';
    public const RECHNUNG_BREGRUENDET_KORREKT = 'RECHNUNG_BREGRUENDET_KORREKT';
    public const KORR_ARTID_FUER_ABR_STORN_SPER_ANG = 'KORREKTE_ARTIKEL_ID_FUER_ABRECHNUNG_STORNIERTER_SPERRAUFTRAG_ANGEGEBEN';
    public const SONSTIGES = 'SONSTIGES';
}
