<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Kalkulationsmethode
{
    public const KEINE = 'KEINE';
    public const STAFFELN = 'STAFFELN';
    public const ZONEN = 'ZONEN';
    public const VORZONEN_GP = 'VORZONEN_GP';
    public const SIGMOID = 'SIGMOID';
    public const BLINDARBEIT_GT_50_PROZENT = 'BLINDARBEIT_GT_50_PROZENT';
    public const BLINDARBEIT_GT_40_PROZENT = 'BLINDARBEIT_GT_40_PROZENT';
    public const AP_GP_ZONEN = 'AP_GP_ZONEN';
    public const LP_INSTALL_LEISTUNG = 'LP_INSTALL_LEISTUNG';
    public const AP_TRANSPORT_ODER_VERTEILNETZ = 'AP_TRANSPORT_ODER_VERTEILNETZ';
    public const AP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNTZ_SIGMOID = 'AP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID';
    public const LP_JAHRESVERBRAUCH = 'LP_JAHRESVERBRAUCH';
    public const LP_TRANSPORT_ODER_VERTEILNETZ = 'LP_TRANSPORT_ODER_VERTEILNETZ';
    public const LP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNTZ_SIGMOID = 'LP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID';
    public const FUNKTIONEN = 'FUNKTIONEN';
    public const VERBR_UE_SLP_FKT_WEITERE_BER_LGK = 'VERBRAUCH_UEBER_SLP_GRENZE_FUNKTIONSBEZOGEN_WEITERE_BERECHNUNG_ALS_LGK';
}
