<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Leistungstyp
{
    public const ARBEITSPREIS_WIRKARBEIT = 'ARBEITSPREIS_WIRKARBEIT';
    public const LEISTUNGSPREIS_WIRKLEISTUNG = 'LEISTUNGSPREIS_WIRKLEISTUNG';
    public const ARBEITSPREIS_BLINDARBEIT_IND = 'ARBEITSPREIS_BLINDARBEIT_IND';
    public const ARBEITSPREIS_BLINDARBEIT_KAP = 'ARBEITSPREIS_BLINDARBEIT_KAP';
    public const GRUNDPREIS = 'GRUNDPREIS';
    public const MEHRMINDERMENGE = 'MEHRMINDERMENGE';
    public const MESSSTELLENBETRIEB = 'MESSSTELLENBETRIEB';
    public const MESSDIENSTLEISTUNG = 'MESSDIENSTLEISTUNG';
    public const MESSDIENSTLEISTUNG_INKL_MESSUNG = 'MESSDIENSTLEISTUNG_INKL_MESSUNG';
    public const ABRECHNUNG = 'ABRECHNUNG';
    public const KONZESSIONS_ABGABE = 'KONZESSIONS_ABGABE';
    public const KWK_UMLAGE = 'KWK_UMLAGE';
    public const OFFSHORE_UMLAGE = 'OFFSHORE_UMLAGE';
    public const ABLAV_UMLAGE = 'ABLAV_UMLAGE';
    public const REGELENERGIE_UMLAGE = 'REGELENERGIE_UMLAGE';
    public const BILANZIERUNG_UMLAGE = 'BILANZIERUNG_UMLAGE';
    public const AUSLESUNG_ZUSAETZLICH = 'AUSLESUNG_ZUSAETZLICH';
    public const ABLESUNG_ZUSAETZLICH = 'ABLESUNG_ZUSAETZLICH';
    public const ABRECHNUNG_ZUSAETZLICH = 'ABRECHNUNG_ZUSAETZLICH';
    public const SPERRUNG = 'SPERRUNG';
    public const ENTSPERRUNG = 'ENTSPERRUNG';
    public const MAHNKOSTEN = 'MAHNKOSTEN';
    public const INKASSOKOSTEN = 'INKASSOKOSTEN';
}
