<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Rechnungstyp
{
    public const ABSCHLUSSRECHNUNG = 'ABSCHLUSSRECHNUNG';
    public const ABSCHLAGSRECHNUNG = 'ABSCHLAGSRECHNUNG';
    public const TURNUSRECHNUNG = 'TURNUSRECHNUNG';
    public const MONATSRECHNUNG = 'MONATSRECHNUNG';
    public const WIMRECHNUNG = 'WIMRECHNUNG';
    public const ZWISCHENRECHNUNG = 'ZWISCHENRECHNUNG';
    public const INTEGRIERTE_13TE_RECHNUNG = 'INTEGRIERTE_13TE_RECHNUNG';
    public const ZUSAETZLICHE_13TE_RECHNUNG = 'ZUSAETZLICHE_13TE_RECHNUNG';
    public const MEHRMINDERMENGENRECHNUNG = 'MEHRMINDERMENGENRECHNUNG';
    public const MSBRECHNUNG = 'MSBRECHNUNG';
    public const KAPAZITAETSRECHNUNG = 'KAPAZITAETSRECHNUNG';
    public const SPERRUNG_INBETRIEBNAHME = 'SPERRUNG_INBETRIEBNAHME';
    public const VERZUGSKOSTEN = 'VERZUGSKOSTEN';
    public const BLINDARBEIT = 'BLINDARBEIT';
    public const SONDERRECHNUNG = 'SONDERRECHNUNG';
}
