<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Sperrauftragsverhinderungsgrund
{
    public const RECHTLICHER_GRUND_FEHLT = 'RECHTLICHER_GRUND_FEHLT';
    public const AKTIVE_ZUTRITTSVERWEIGERUNG = 'AKTIVE_ZUTRITTSVERWEIGERUNG';
    public const PASSIVE_ZUTRITTSVERWEIGERUNG = 'PASSIVE_ZUTRITTSVERWEIGERUNG';
    public const ANDERER_VERHINDERUNGSGRUND = 'ANDERER_VERHINDERUNGSGRUND';
    public const TATSAECHLICHER_VERHINDERUNGSGRUND = 'TATSAECHLICHER_VERHINDERUNGSGRUND';
    public const TECHNISCHER_VERHINDERUNGSGRUND = 'TECHNISCHER_VERHINDERUNGSGRUND';
    public const ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN = 'ANSCHLUSSNUTZER_WURDE_NICHT_ANGETROFFEN';
}
