<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Statusanlass
{
    public const KOMMUNIKATIONSSTOERUNG = 'KOMMUNIKATIONSSTOERUNG';
    public const STATUS_GERAETEWECHSEL = 'STATUS_GERAETEWECHSEL';
    public const MESSEINRICHTUNG_GESTOERT_DEFEKT = 'MESSEINRICHTUNG_GESTOERT_DEFEKT';
    public const KEINE_STOERUNG_FESTSTELLBAR = 'KEINE_STOERUNG_FESTSTELLBAR';
    public const STOERUNGSBEHEBUNG_NICHT_MOEGLICH = 'STOERUNGSBEHEBUNG_NICHT_MOEGLICH';
    public const REPARATUR_OHNE_GERAETEWECHSEL = 'REPARATUR_OHNE_GERAETEWECHSEL';
}
