<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Status
{
    public const KUNDENSELBSTABLESUNG = 'KUNDENSELBSTABLESUNG';
    public const LEERSTAND = 'LEERSTAND';
    public const REALER_ZAEHLERUEBERLAUF_GEPRUEFT = 'REALER_ZAEHLERUEBERLAUF_GEPRUEFT';
    public const PLAUSIBEL_WG_KONTROLLABLESUNG = 'PLAUSIBEL_WG_KONTROLLABLESUNG';
    public const PLAUSIBEL_WG_KUNDENHINWEIS = 'PLAUSIBEL_WG_KUNDENHINWEIS';
    public const AUSTAUSCH_DES_ERSATZWERTES = 'AUSTAUSCH_DES_ERSATZWERTES';
    public const RECHENWERT = 'RECHENWERT';
    public const BASIS_MME = 'BASIS_MME';
    public const VERGLEICHSMESSUNG_GEEICHT = 'VERGLEICHSMESSUNG_GEEICHT';
    public const VERGLEICHSMESSUNG_NICHT_GEEICHT = 'VERGLEICHSMESSUNG_NICHT_GEEICHT';
    public const MESSWERTNACHBILDUNG_AUS_GEEICHTEN_WERTEN = 'MESSWERTNACHBILDUNG_AUS_GEEICHTEN_WERTEN';
    public const MESSWERTNACHBILDUNG_AUS_NICHT_GEEICHTEN_WERTEN = 'MESSWERTNACHBILDUNG_AUS_NICHT_GEEICHTEN_WERTEN';
    public const INTERPOLATION = 'INTERPOLATION';
    public const HALTEWERT = 'HALTEWERT';
    public const BILANZIERUNG_NETZABSCHNITT = 'BILANZIERUNG_NETZABSCHNITT';
    public const HISTORISCHE_MESSWERTE = 'HISTORISCHE_MESSWERTE';
    public const STATISTISCHE_METHODE = 'STATISTISCHE_METHODE';
    public const AUFTEILUNG = 'AUFTEILUNG';
    public const VERWENDUNG_VON_WERTEN_DES_STOERMENGENZAEHLWERKS = 'VERWENDUNG_VON_WERTEN_DES_STOERMENGENZAEHLWERKS';
    public const UMGANGS_UND_KORREKTURMENGEN = 'UMGANGS_UND_KORREKTURMENGEN';
    public const ANGABEN_MESSLOKATION = 'ANGABEN_MESSLOKATION';
    public const KEIN_ZUGANG = 'KEIN_ZUGANG';
    public const KOMMUNIKATIONSSTOERUNG = 'KOMMUNIKATIONSSTOERUNG';
    public const NETZAUSFALL = 'NETZAUSFALL';
    public const SPANNUNGSAUSFALL = 'SPANNUNGSAUSFALL';
    public const STATUS_GERAETEWECHSEL = 'STATUS_GERAETEWECHSEL';
    public const KALIBRIERUNG = 'KALIBRIERUNG';
    public const GERAET_ARBEITET_AUSSERHALB_DER_BETRIEBSBEDINGUNGEN = 'GERAET_ARBEITET_AUSSERHALB_DER_BETRIEBSBEDINGUNGEN';
    public const MESSEINRICHTUNG_GESTOERT_DEFEKT = 'MESSEINRICHTUNG_GESTOERT_DEFEKT';
    public const UNSICHERHEIT_MESSUNG = 'UNSICHERHEIT_MESSUNG';
    public const BERUECKSICHTIGUNG_STOERMENGENZAEHLWERK = 'BERUECKSICHTIGUNG_STOERMENGENZAEHLWERK';
    public const MENGENUMWERTUNG_VOLLSTAENDIG = 'MENGENUMWERTUNG_VOLLSTAENDIG';
    public const UHRZEIT_GESTELLT_SYNCHRONISATION = 'UHRZEIT_GESTELLT_SYNCHRONISATION';
    public const MESSWERT_UNPLAUSIBEL = 'MESSWERT_UNPLAUSIBEL';
    public const FALSCHER_WANDLERFAKTOR = 'FALSCHER_WANDLERFAKTOR';
    public const FEHLERHAFTE_ABLESUNG = 'FEHLERHAFTE_ABLESUNG';
    public const AENDERUNG_DER_BERECHNUNG = 'AENDERUNG_DER_BERECHNUNG';
    public const UMBAU_DER_MESSLOKATION = 'UMBAU_DER_MESSLOKATION';
    public const DATENBEARBEITUNGSFEHLER = 'DATENBEARBEITUNGSFEHLER';
    public const BRENNWERTKORREKTUR = 'BRENNWERTKORREKTUR';
    public const Z_ZAHL_KORREKTUR = 'Z_ZAHL_KORREKTUR';
    public const STOERUNG_DEFEKT_MESSEINRICHTUNG = 'STOERUNG_DEFEKT_MESSEINRICHTUNG';
    public const AENDERUNG_TARIFSCHALTZEITEN = 'AENDERUNG_TARIFSCHALTZEITEN';
    public const TARIFSCHALTGERAET_DEFEKT = 'TARIFSCHALTGERAET_DEFEKT';
    public const IMPULSWERTIGKEIT_NICHT_AUSREICHEND = 'IMPULSWERTIGKEIT_NICHT_AUSREICHEND';
    public const ENERGIEMENGE_IN_UNGEMESSENEM_ZEITINTERVALL = 'ENERGIEMENGE_IN_UNGEMESSENEM_ZEITINTERVALL';
    public const ENERGIEMENGE_AUS_DEM_UNGEPAIRTEN_ZEITINTERVALL = 'ENERGIEMENGE_AUS_DEM_UNGEPAIRTEN_ZEITINTERVALL';
    public const WARTUNGSARBEITEN_AN_GEEICHTEM_MESSGERAET = 'WARTUNGSARBEITEN_AN_GEEICHTEM_MESSGERAET';
    public const GESTOERTE_WERTE = 'GESTOERTE_WERTE';
    public const WARTUNGSARBEITEN_AN_EICHRECHTSKONFORMEN_MESSGERAETEN = 'WARTUNGSARBEITEN_AN_EICHRECHTSKONFORMEN_MESSGERAETEN';
    public const KONSISTENZ_UND_SYNCHRONPRUEFUNG = 'KONSISTENZ_UND_SYNCHRONPRUEFUNG';
    public const GRUND_ANGABEN_MESSLOKATION = 'GRUND_ANGABEN_MESSLOKATION';
    public const UMSTELLUNG_GASQUALITAET = 'UMSTELLUNG_GASQUALITAET';
    public const ZAEHLERSTAND_1 = 'ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT';
    public const ZAEHLERSTAND_2 = 'ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_VORHANDEN_UND_KOMMUNIZIERT';
    public const ZAEHLERSTAND_3 = 'ZAEHLERSTAND_ZUM_BEGINN_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG';
    public const ZAEHLERSTAND_4 = 'ZAEHLERSTAND_ZUM_ENDE_DER_ANGEGEBENEN_ENERGIEMENGE_NICHT_VORHANDEN_DA_MENGENABGRENZUNG';
    public const GESCHEITERT = 'GESCHEITERT';
    public const AUSGEBAUT = 'AUSGEBAUT';
}
