<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface StatusArt
{
    public const PLAUSIBILISIERUNGSHINWEIS = 'PLAUSIBILISIERUNGSHINWEIS';
    public const ERSATZWERTBILDUNGSVERFAHREN = 'ERSATZWERTBILDUNGSVERFAHREN';
    public const KORREKTURGRUND = 'KORREKTURGRUND';
    public const GRUND_ERSATZWERTBILDUNGSVERFAHREN = 'GRUND_ERSATZWERTBILDUNGSVERFAHREN';
    public const GASQUALITAET = 'GASQUALITAET';
    public const MESSKLASSIFIZIERUNG = 'MESSKLASSIFIZIERUNG';
}
