<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface StatusErzeugendeMarktlokation
{
    public const EINSPEISEVERGUETUNG_PARAGRAPH_37 = 'EINSPEISEVERGUETUNG_PARAGRAPH_37';
    public const GEFOERDERTE_DIREKTVERMARKTUNG = 'GEFOERDERTE_DIREKTVERMARKTUNG';
    public const SONSTIGE_DIREKTVERMARKTUNG = 'SONSTIGE_DIREKTVERMARKTUNG';
    public const VERMARKTUNG_OHNE_GESETZL_VERGUETUNG = 'VERMARKTUNG_OHNE_GESETZL_VERGUETUNG';
    public const KWKG_VERGUETUNG = 'KWKG_VERGUETUNG';
    public const EINSPEISEVERGUETUNG_PARAGRAPH_38_AUSFALLVERGUETUNG = 'EINSPEISEVERGUETUNG_PARAGRAPH_38_AUSFALLVERGUETUNG';
}
