<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface VerwendungszweckValue
{
    public const NETZNUTZUNGSABRECHNUNG = 'NETZNUTZUNGSABRECHNUNG';
    public const BILANZKREISABRECHNUNG = 'BILANZKREISABRECHNUNG';
    public const MEHRMINDERMENGENABRECHNUNG = 'MEHRMINDERMENGENABRECHNUNG';
    public const ENDKUNDENABRECHNUNG = 'ENDKUNDENABRECHNUNG';
    public const UEBERMITTLUNG_AN_DAS_HKNR = 'UEBERMITTLUNG_AN_DAS_HKNR';
    public const BLINDARBEITSABRECHNUNG = 'BLINDARBEITSABRECHNUNG';
    public const ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS = 'ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS';
}
