<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Interface;

interface Zaehlertyp
{
    public const DREHSTROMZAEHLER = 'DREHSTROMZAEHLER';
    public const BALGENGASZAEHLER = 'BALGENGASZAEHLER';
    public const DREHKOLBENZAEHLER = 'DREHKOLBENZAEHLER';
    public const SMARTMETER = 'SMARTMETER';
    public const LEISTUNGSZAEHLER = 'LEISTUNGSZAEHLER';
    public const MAXIMUMZAEHLER = 'MAXIMUMZAEHLER';
    public const TURBINENRADGASZAEHLER = 'TURBINENRADGASZAEHLER';
    public const ULTRASCHALLGASZAEHLER = 'ULTRASCHALLGASZAEHLER';
    public const WECHSELSTROMZAEHLER = 'WECHSELSTROMZAEHLER';
    public const WIRBELGASZAEHLER = 'WIRBELGASZAEHLER';
    public const MESSDATENREGISTRIERGERAET = 'MESSDATENREGISTRIERGERAET';
    public const ELEKTRONISCHERHAUSHALTSZAEHLER = 'ELEKTRONISCHERHAUSHALTSZAEHLER';
    public const SONDERAUSSTATTUNG = 'SONDERAUSSTATTUNG';
    public const WASSERZAEHLER = 'WASSERZAEHLER';
    public const MODERNEMESSEINRICHTUNG = 'MODERNEMESSEINRICHTUNG';
}
