<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Cdoc;

enum EventName: string
{
    case ECS_LIEFERBEGINN = 'ECS_LIEFERBEGINN';
    case START_MALOIDENT = 'START_MALOIDENT';
    case START_KUENDIGUNG = 'START_KUENDIGUNG';
    case START_LIEFERBEGINN = 'START_LIEFERBEGINN';
    case START_LIEFERENDE = 'START_LIEFERENDE';
    case START_VERSAND_SDAE = 'START_VERSAND_SDAE';
    case START_ABMELDEANFRAGE = 'START_ABMELDEANFRAGE';
    case START_AUFH_ZUK_ZUORDNUNG = 'START_AUFH_ZUK_ZUORDNUNG';
    case START_ENDE_ZUORDNUNG = 'START_ENDE_ZUORDNUNG';
    case START_ABR_NN = 'START_ABR_NN';
    case START_ABR_BK = 'START_ABR_BK';
    case START_EINRICHTUNG_KONFIG = 'START_EINRICHTUNG_KONFIG';
    case START_BERECHNUNGSFORMEL = 'START_BERECHNUNGSFORMEL';
    case START_WIEDERHERST_LB = 'START_WIEDERHERST_LB';
    case START_EOG = 'START_EOG';
    case START_ANFORDERUNG_MESSWERTE = 'START_ANFORDERUNG_MESSWERTE';
    case START_BESTELLUNG_ABRECHNUNGSDATEN = 'START_BESTELLUNG_ABRECHNUNGSDATEN';
    case START_ERHEBUNG_MESSWERTE = 'START_ERHEBUNG_MESSWERTE';
    case START_BESTELLUNG_SDAE = 'START_BESTELLUNG_SDAE';
    case START_VERSAND_LIEFERSCHEIN = 'START_VERSAND_LIEFERSCHEIN';
    case START_VERSAND_ANTWORT_NNA = 'START_VERSAND_ANTWORT_NNA';
    case START_ANFRAGE_KONFIGURATION = 'START_ANFRAGE_KONFIGURATION';
    case START_BESTELLUNG_KONFIGURATION = 'START_BESTELLUNG_KONFIGURATION';
    case START_BESTELLUNG_ANGEBOT_KONFIGURATION = 'START_BESTELLUNG_ANGEBOT_KONFIGURATION';
    case START_BESTELLUNG_ZAEHLZEITDEFINITION = 'START_BESTELLUNG_ZAEHLZEITDEFINITION';
    case START_VERSAND_BESTANDSLISTE = 'START_VERSAND_BESTANDSLISTE';
    case START_VERSAND_ANF_STORNO = 'START_VERSAND_ANF_STORNO';
    case START_VERSAND_BEST_BEEND_KONFIG = 'START_VERSAND_BEST_BEEND_KONFIG';
    case START_VERSAND_STORNO_MSCONS = 'START_VERSAND_STORNO_MSCONS';
    case START_BEGINN_MSB = 'START_BEGINN_MSB';
    case START_ENDE_MSB = 'START_ENDE_MSB';
    case START_KUENDIGUNG_MSB = 'START_KUENDIGUNG_MSB';
    case START_GESCHAEFTSDATENANFRAGE = 'START_GESCHAEFTSDATENANFRAGE';
    case START_VERSAND_PREISBLATT_IMS = 'START_VERSAND_PREISBLATT_IMS';
}
