<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Cdoc;

enum EventName: string
{
    case ECS_LIEFERBEGINN = 'ECS_LIEFERBEGINN';
    case START_MALOIDENT = 'START_MALOIDENT';
    case START_KUENDIGUNG = 'START_KUENDIGUNG';
    case START_LIEFERBEGINN = 'START_LIEFERBEGINN';
    case START_LIEFERENDE = 'START_LIEFERENDE';
    case START_VERSAND_SDAE = 'START_VERSAND_SDAE';
    case START_ABMELDEANFRAGE = 'START_ABMELDEANFRAGE';
    case START_AUFH_ZUK_ZUORDNUNG = 'START_AUFH_ZUK_ZUORDNUNG';
    case START_ENDE_ZUORDNUNG = 'START_ENDE_ZUORDNUNG';
    case START_ABR_NN = 'START_ABR_NN';
    case START_ABR_BK = 'START_ABR_BK';
    case START_EINRICHTUNG_KONFIG = 'START_EINRICHTUNG_KONFIG';
    case START_BERECHNUNGSFORMEL = 'START_BERECHNUNGSFORMEL';
    case START_WIEDERHERST_LB = 'START_WIEDERHERST_LB';
    case START_EOG = 'START_EOG';
}
